### ISSUE TITLE
doubt in sample

### ISSUE THREAD

**Issue by nkv16786** [jackqq/xTomcat#1]
what should be given in $installsource

**Comment by jackqq** [comment]
$InstallSource should be the base path for all the installation files. For example, I defined it in my configuration data file, excerpted below:

```PowerShell
@{
    AllNodes = @(
       @{
            NodeName = '*'
            InstallSource = "\\my-test-domain\install"
        }
    );
}
```

And the sample configuration can be called this way:

```PowerShell
TomcatConfig -OutputPath .\output -ConfigurationData ".\configdata\mydev-config.psd1"
```
